using Azure;
using Azure.Search.Documents.Models;
using Dfe.Data.Common.Infrastructure.CognitiveSearch.SearchByKeyword;
using Dfe.Data.SearchPrototype.Common.Mappers;
using Dfe.Data.SearchPrototype.Infrastructure.Options;
using Dfe.Data.SearchPrototype.Infrastructure.Tests.TestDoubles;
using Dfe.Data.SearchPrototype.SearchForEstablishments;
using Dfe.Data.SearchPrototype.SearchForEstablishments.Models;
using FluentAssertions;
using Moq;
using Xunit;

namespace Dfe.Data.SearchPrototype.Infrastructure.Tests;

public sealed class CognitiveSearchServiceAdapterTests
{
    private static CognitiveSearchServiceAdapter<Establishment> CreateServiceAdapterWith(
        ISearchByKeywordService searchByKeywordService,
        ISearchOptionsFactory searchOptionsFactory,
        IMapper<Pageable<SearchResult<Establishment>>, EstablishmentResults> searchResponseMapper,
        IMapper<Dictionary<string, IList<Azure.Search.Documents.Models.FacetResult>>, EstablishmentFacets> facetsMapper
       ) =>
           new(searchByKeywordService, searchOptionsFactory, searchResponseMapper, facetsMapper);

    [Fact]
    public async Task Search_WithValidSearchContext_CallsMappers()
    {
        // arrange
        var mockService = new SearchServiceMockBuilder()
            .WithSearchOptions("SearchKeyword", "TargetCollection")
            .WithSearchResults(
                new SearchResultFakeBuilder()
                .WithSearchResults()
                .Create())
            .WithFacets(
                new FacetsResultsFakeBuilder()
                .WithAutoGeneratedFacet()
                .Create())
            .Create();
        var mockSearchOptionsFactory = SearchOptionsFactoryTestDouble.MockSearchOptionsFactory();
        var mockEstablishmentResultsMapper = PageableSearchResultsToEstablishmentResultsMapperTestDouble.DefaultMock();
        var mockFacetsMapper = AzureFacetResultToEstablishmentFacetsMapperTestDouble.DefaultMock();

        ISearchServiceAdapter cognitiveSearchServiceAdapter =
            CreateServiceAdapterWith(
                mockService,
                mockSearchOptionsFactory,
                mockEstablishmentResultsMapper,
                mockFacetsMapper);

        // act
        SearchResults? response =
            await cognitiveSearchServiceAdapter.SearchAsync(
                new SearchContext(
                    searchKeyword: "SearchKeyword",
                    targetCollection: "TargetCollection"));

        // assert
        Mock.Get(mockService).Verify();
        Mock.Get(mockSearchOptionsFactory).Verify(
            SearchOptionsFactoryTestDouble.SearchOption(), Times.Once());
        Mock.Get(mockEstablishmentResultsMapper).Verify(
            mapper => mapper.MapFrom(It.IsAny<Pageable<SearchResult<Establishment>>>()),Times.Once());
        Mock.Get(mockFacetsMapper).Verify(
            mapper => mapper.MapFrom(It.IsAny<Dictionary<string, IList<Azure.Search.Documents.Models.FacetResult>>>()), Times.Once());
    }

    [Fact]
    public async Task Search_WithNoFacetsReturned_ReturnsNullFacets()
    {
        // arrange
        var mockService = new SearchServiceMockBuilder()
            .WithSearchOptions("SearchKeyword", "TargetCollection")
            .WithSearchResults(
                new SearchResultFakeBuilder()
                .WithSearchResults()
                .Create())
            .Create();
        var mockSearchOptionsFactory = SearchOptionsFactoryTestDouble.MockSearchOptionsFactory();
        var mockEstablishmentResultsMapper = PageableSearchResultsToEstablishmentResultsMapperTestDouble.DefaultMock();
        var mockFacetsMapper = AzureFacetResultToEstablishmentFacetsMapperTestDouble.DefaultMock();

        ISearchServiceAdapter cognitiveSearchServiceAdapter =
            CreateServiceAdapterWith(
                mockService,
                mockSearchOptionsFactory,
                mockEstablishmentResultsMapper,
                mockFacetsMapper);

        // act
        SearchResults? response =
            await cognitiveSearchServiceAdapter.SearchAsync(
                new SearchContext(
                    searchKeyword: "SearchKeyword",
                    targetCollection: "TargetCollection"));

        // assert
        response.Should().NotBeNull();
        response.Facets.Should().BeNull();
    }

    [Fact]
    public Task Search_WithNoSearchOptions_ThrowsApplicationException()
    {
        var mockServiceBuilder = new SearchServiceMockBuilder();
        var mockService = mockServiceBuilder.MockSearchService("SearchKeyword", "TargetCollection");
        var mockSearchOptionsFactory = SearchOptionsFactoryTestDouble.MockForNoOptions();
        var mockEstablishmentResultsMapper = PageableSearchResultsToEstablishmentResultsMapperTestDouble.DefaultMock();
        var mockFacetsMapper = AzureFacetResultToEstablishmentFacetsMapperTestDouble.DefaultMock();

        // arrange
        ISearchServiceAdapter cognitiveSearchServiceAdapter =
            CreateServiceAdapterWith(
                mockService,
                mockSearchOptionsFactory,
                mockEstablishmentResultsMapper,
                mockFacetsMapper);

        // act.
        return cognitiveSearchServiceAdapter
            .Invoking(async serviceAdapter =>
                await serviceAdapter.SearchAsync(
                    new SearchContext(
                        searchKeyword: "SearchKeyword",
                        targetCollection: "TargetCollection")))
            .Should()
            .ThrowAsync<ApplicationException>()
            .WithMessage("Search options cannot be derived for TargetCollection.");
    }

    [Fact]
    public async Task Search_WithNoResultsReturned_ReturnsEmptyResults()
    {
        // arrange
        var mockServiceBuilder = new SearchServiceMockBuilder();
        var mockService = mockServiceBuilder.MockSearchService("SearchKeyword", "TargetCollection");
        var mockSearchOptionsFactory = SearchOptionsFactoryTestDouble.MockSearchOptionsFactory();
        var mockEstablishmentResultsMapper = PageableSearchResultsToEstablishmentResultsMapperTestDouble
            .MockFor(new EstablishmentResults());
        var mockFacetsMapper = AzureFacetResultToEstablishmentFacetsMapperTestDouble.DefaultMock();

        ISearchServiceAdapter cognitiveSearchServiceAdapter =
            CreateServiceAdapterWith(
                mockService,
                mockSearchOptionsFactory,
                mockEstablishmentResultsMapper,
                mockFacetsMapper);

        // act.
        var response = await cognitiveSearchServiceAdapter.SearchAsync(new SearchContext(
                            searchKeyword: "SearchKeyword",
                            targetCollection: "TargetCollection"));

        // assert
        response.Should().NotBeNull();
        response.Establishments.Should().NotBeNull();
        response.Establishments!.Establishments.Should().BeEmpty();
    }

    [Fact]
    public Task Search_MapperThrowsException_ExceptionPassesThrough()
    {
        // arrange
        var mockServiceBuilder = new SearchServiceMockBuilder();
        var mockService = mockServiceBuilder.MockSearchService("SearchKeyword", "TargetCollection");
        var mockSearchOptionsFactory = SearchOptionsFactoryTestDouble.MockSearchOptionsFactory();
        var mockEstablishmentResultsMapper = PageableSearchResultsToEstablishmentResultsMapperTestDouble.MockMapperThrowingArgumentException();
        var mockFacetsMapper = AzureFacetResultToEstablishmentFacetsMapperTestDouble.DefaultMock();

        ISearchServiceAdapter cognitiveSearchServiceAdapter =
            CreateServiceAdapterWith(
                mockService,
                mockSearchOptionsFactory,
                mockEstablishmentResultsMapper,
                mockFacetsMapper);

        // act, assert.
        return cognitiveSearchServiceAdapter
            .Invoking(adapter => adapter.SearchAsync(new SearchContext(
                            searchKeyword: "SearchKeyword",
                            targetCollection: "TargetCollection")))
            .Should()
            .ThrowAsync< ArgumentException>();
    }
}
